# This workflow will build a Java project with Maven

name: maven 编译检查

on:
  push:
    branches: [ master,dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'zulu'

      - name: mvn clean install
        run: mvn clean install -Pboot -Dmaven.compiler.release=${{ matrix.java-version }}

      - name: mvn clean install
        run: mvn clean install -Pcloud -Dmaven.compiler.release=${{ matrix.java-version }}
